authors/urls.py
from django.urls import path
from . import views 

app_name = 'authors'
urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('register/create/', views.register_create, name="register_create"),
    path('login/create/', views.login_create, name="login_create"),
    path('logout/', views.logout_view, name="logout"),
]

projeto_django1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('authors/', include('authors.urls')),
]

# habilitando os arquivos estaticos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views 

app_name = 'recipes'
urlpatterns = [
    path('', views.home, name="home"),
    path('recipes/search/', views.search, name="search"),
    path('recipe/<int:id>/', views.recipe, name="recipe"),
    path('recipe/category/<int:category_id>/', views.category, name="category"),

]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self) -> str:
        return self.name

class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_step = models.TextField()
    preparation_step_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d', blank=True, default='')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self) -> str:
        return self.title

recipes/views.py
from django.http.response import Http404
from django.shortcuts import render, get_object_or_404, get_list_or_404
from recipes.models import Recipe
from django.db.models import Q
from django.core.paginator import Paginator
from utils.pagination import make_pagination
import os
from django.contrib import messages

PER_PAGE =  int(os.environ.get('PER_PAGE', 6))
def home(request):

    recipes = Recipe.objects.filter(is_published= True).all().order_by('-id')

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)
    return render(request, 'recipes/pages/home.html', context={"recipes": page_obj, 'pagination_range': pagination_range})

def category(request, category_id: int):
    recipe_category = get_list_or_404(Recipe.objects.filter(
        category__id=category_id,
        is_published = True,)
        .order_by('-id'))

    page_obj, pagination_range = make_pagination(request, recipe_category, PER_PAGE)
    return render(request, 'recipes/pages/category.html',
                  context={"recipes": page_obj,
                            "pagination_range": pagination_range,
                           'title': f'{recipe_category[0].category.name}  - Category '})

def recipe(request, id: int):
    recipe = get_object_or_404(Recipe,
        pk=id,
        is_published = True, )
    return render(request, 'recipes/pages/recipe-view.html',
                  context={"recipe": recipe, 'is_detail_page': True}
                  )

def search(request):

    search_text = str(request.GET.get('search')).strip()

    if not search_text:
        raise Http404()
    
    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains = search_text) |
            Q(description__icontains = search_text)
        ),
        is_published = True
    )

    page_obj, pagination_range = make_pagination(request, recipes, PER_PAGE)
    return render(request, 'recipes/pages/search.html',{
        'page_title': f'pesquisa por "{search_text}"',
        'search_text': search_text,
        'recipes': page_obj,
        "pagination_range": pagination_range,
        "additional_url_query":f'&search={search_text}'
    })

recipes/templates/recipes/partials/head.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/solid.min.css" integrity="sha512-/r+0SvLvMMSIf41xiuy19aNkXxI+3zb/BN8K9lnDDWI09VM0dwgTMzK7Qi5vv5macJ3VH4XZXr60ip7v13QnmQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/brands.min.css" integrity="sha512-EJp8vMVhYl7tBFE2rgNGb//drnr1+6XKMvTyamMS34YwOEFohhWkGq13tPWnK0FbjSS6D8YoA3n3bZmb3KiUYA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/fontawesome.min.css" integrity="sha512-B46MVOJpI6RBsdcU307elYeStF2JKT87SsHZfRSkjVi4/iZ3912zXi45X5/CBr/GbCyLx6M1GQtTKYRd52Jxgw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">

recipes/templates/recipes/partials/recipe.html
            <div class=" recipe recipe-list-item">
                {% if recipe.cover %}
                <div class="recipe-list-cover">
                    <a href="{% url "recipes:recipe" recipe.id %}">
                        <img src="{{recipe.cover.url}}" alt="temporario">
                    </a>
                </div>
                {% endif %}
                 <div class="recipe-title-container">
                    <h2 class="recipe-title">
                        <a href="{% url "recipes:recipe" recipe.id %}">
                            {{recipe.title}}
                        </a>
                    </h2>
                 </div>

                 <div class="recipe-author">
                    <span class="recipe-author-item">
                        <i class="fas fa-user"></i>
                        {% if recipe.author is not None %}
                            {% if recipe.author.first_name %}
                            {{recipe.author.first_name}}
                            {% else %}
                            {{recipe.author.username}}
                            {% endif %}
                        {% else %}
                            <span>Desconhecido</span>
                        {% endif %}
                    </span>

                    <span class="recipe-author-item">
                        <i class="fas fa-calendar-alt"></i>
                        {{ recipe.created_at|date:"d/m/Y" }}
                    </span>
                    {% if recipe.category is not None %}
                        <span class="recipe-author-item">
                            <a href="{% url "recipes:category" recipe.category.id %}">
                                <i class="fas fa-layer-group"></i>
                                <span>{{recipe.category.name}}</span>
                            </a>
                        </span>
                    {% endif %}
                 </div>

                 <div class="recipe-content">
                    <p>{{recipe.description}}</p>
                 </div>

                 <div class="recipe-meta-container">
                    <div class="recipe-meta recipe-preparation">
                        <h3 class="recipe-meta-title"><i class="fas fa-stopwatch"></i>Preparo</h3>
                        <div class="recipe-meta-text">
                            {{recipe.preparation_time}} {{recipe.preparation_time_unit}}
                        </div>
                    </div>
                    <div class="recipe-meta recipe-servings">
                         <h3 class="recipe-meta-title"><i class="fas fa-pizza-slice"></i>Porções</h3>
                         <div class="recipe-meta-text">
                            {{recipe.servings}} porções
                         </div>
                     </div>
                    </div>
                    <footer class="recipe-footer">
                        {% if is_detail_page is not True %}
                            <a href="{% url "recipes:recipe" recipe.id %}" class="recipe-reade-more button button-dark button-full-width">
                                <i class="fas fa-eye"></i>
                                <span>ver mais...</span>
                            </a>
                        {% endif %}
                    </footer>

                    {% if is_detail_page is True %}
                        <div class="preparation-steps">
                            {% if recipe.preparation_step_is_html is True %}
                                {{recipe.preparation_step|safe}}
                            {% else %}
                                {{recipe.preparation_step|linebreaksbr}}
                            {% endif %}
                        </div>
                    {% endif %}

            </div>